### ISSUE TITLE
Crankshaft Robot

### ISSUE THREAD

**Issue by knowbody** [gocardless/gocardless-pro-ruby#13]
Who is a Crankshaft Robot?

**Comment by jackfranklin** [comment]
Crankshaft is our internal GoCardless robot that automatically deploys new versions of the Ruby client when the files that generate the client change (this entire repo is auto-generated for us).

We want to open source Crankshaft and the relevant tooling but we're not at a stage to do so, not just yet.

**Comment by knowbody** [comment]
that's what I thought :+1: 

I like the name I bet Pete chose it
