### ISSUE TITLE
Should the Event resource have an 'organisation' attr_reader?

### ISSUE THREAD

**Issue by capowell** [gocardless/gocardless-pro-ruby#19]
The organisation in the links hash is used by partners to work out which gocardless account an event relates to. At the moment, I think it is only accessible via: event.to_h['links']['organisation']?

**Comment by greysteil** [comment]
Good spot - it's getting missed because we only serialise it for OAuth applications. I'll update the schema now, and should have an updated version of the gem for you on Monday morning.

**Comment by greysteil** [comment]
@capowell - fixed on master. We'll cut a new release by latest Monday evening.

**Comment by capowell** [comment]
Hi Greg

> @capowell <https://github.com/capowell> - fixed on master. We'll cut a new release by latest Monday evening.

Thanks very much for the speedy fix!

Chris.

**Comment by petehamilton** [comment]
Hi @capowell, just cut [v1.0.3](https://github.com/gocardless/gocardless-pro-ruby/releases/tag/v1.0.3), which should fix this issue for you.
