### ISSUE TITLE
Global access to client

### ISSUE THREAD

**Issue by carlosbutler** [gocardless/gocardless-pro-ruby#22]
I created a module for the client loaded at initialisation:
```
# config/init/gocardless.rb
module Gocardless
  def self.client
    Thread.main[:gocardless_client] ||= GoCardlessPro::Client.new(
      access_token: "gocardless_access_token",
      environment: (Rails.env.production? ? :live : :sandbox)
    )
  end
end
```

```
# app/controllers/whatever_controller.rb
class Controller
  def method
    client = Gocardless.client
  end
end
```

I could not find any other appropriate way of setting config options. Please could you clarify if this method is safe and most appropriate?

Thanks

**Comment by timrogers** [comment]
This seems fairly sensible to me! 

We approach this in two different ways in different places internally - in some applications we just instantiate a client where it's used (i.e. in the class where we're making API calls), whereas in others we take an approach like yours with one instance:

```ruby
class GoCardless
  def self.client
    @client ||= GoCardless::Client.new(client_options)
  end

  def self.client_options
    # ...
  end
end
```

**Comment by carlosbutler** [comment]
Okay thanks for confirming that.

@timrogers on another note, do you guys have a webhook limit max size? Can't seem to find it in the docs (and need to know for column size in DB).

Cheers

**Comment by cba7** [comment]
Or indeed a timeout thus creating an error on your side, i.e. if saving the webook, processing it, and giving a response takes 10 seconds because we have a bottleneck somewhere.

**Comment by timrogers** [comment]
@carlosbutler We don't have any published size limit. At the moment, you can have up to 1000 events in a single webhook in a worst case scenario, so you should be able to handle that.

@cba7 Right now, we have a timeout of 10 seconds, but this is subject to change.

**Comment by jacobpgn** [comment]
Just to add to that: in the event of timeouts - or other failures to deliver the webhook - we'll retry each webhook up to 10 times at increasing intervals. 

I'm going to close this now as it looks like the original issue is solved. Please do feel free to open another issue if there are any problems with the library, or you can reach out to our developer support team on api@gocardless.com if you have any questions about usage!
