### ISSUE TITLE
Old Faraday dependency

### ISSUE THREAD

**Issue by Odaeus** [gocardless/gocardless-pro-ruby#24]
Are you able to update Faraday to a more recent version (the latest is 0.12.x)? As it's causing an unwanted downgrade to version 0.10 in my Gemfile.

**Comment by timrogers** [comment]
I suspect it'll work! Let me have a quick go and get back to you.

**Comment by timrogers** [comment]
The change is now live in https://github.com/gocardless/gocardless-pro-ruby/commit/2148614f6068f9182018d0abef054f1ab48d926f - all seems to work! We'll look to release this to RubyGems soon, but for now you can just load it from GitHub by specifying that commit if you like.

**Comment by Odaeus** [comment]
Wonderful, thank you!
