### ISSUE TITLE
Creating payment with existing Idempotency-Key

### ISSUE THREAD

**Issue by michal-g-iRonin** [gocardless/gocardless-pro-ruby#39]
Hi! When i creating new payment, with conflicting `Idempotency-Key`, library returns the existing one. There is any way to find out which one is returned - newly submitted or that one created before? i mean in that case gem always return some object and result with `success: true`, but i really want to know about conflict ;)

**Comment by mottalrd** [comment]
@nickcampbell18 any feedback on this?

**Comment by nickcampbell18** [comment]
Sorry for the delay!

Great points; this is really annoying. What kind of interface would you like to see? Here's a couple of options I could think of:

### 1. Raise on idempotency failure

```ruby
@client = GoCardlessPro::Client.new(
  raise_on_idempotency_conflict: true, # this would otherwise be a breaking change
)

begin
  @client.payments.create(...)
rescue GoCardlessPro::IdempotencyConflict
  # do something else
end
```

### 2. Annotate the response object

```ruby
response = @client.payments.create(../)

if response.idempotency_conflict?
  # do something else
end
```

---

I'm open to other suggestions though, and if you fancy opening a pull request we would also greatly appreciate it!

**Comment by mottalrd** [comment]
Thank you @nickcampbell18 . 

For us (1) would be better. We will investigate how long will it take for us to open a PR and will get back to you this week. If we can't, when would you expect to be able to work on that?

Looking forward to hear back!

**Comment by nickcampbell18** [comment]
Excellent, thanks. It probably would only take a day or so to build this change, but our team is pretty stacked at the moment so we couldn't commit any timeframes for quite a while, sorry - I suggest you either patch it or submit a pull request and we can take it from there 👍

**Comment by michal-g-iRonin** [comment]
#41 proposed changes :)

**Comment by mottalrd** [comment]
Thank you @nickcampbell18 and @michal-g-iRonin !
