### ISSUE TITLE
Readme Idempotency-Key instructions incorrect

### ISSUE THREAD

**Issue by scottish613** [gocardless/gocardless-pro-ruby#44]
I was trying to test usage of the `Idempotency-Key` header in the client.

The readme directs me to pass a custom idempotency key like so:
```
headers: {
  "Idempotency-Key": "1f9630a9-0487-418d-bd37-8b77793c9985"
}
```

That will create the entry with a symbolic key, which is later masked by the default, which uses a string key (https://github.com/gocardless/gocardless-pro-ruby/blob/master/lib/gocardless_pro/request.rb#L35). I'm suspecting that both are getting sent to the API, but custom key is getting ignored because it's either first or last in the headers list.

I'd suggest either updating the readme to use `"Idempotency-Key" => ...`, or running one of `stringify_keys`, `with_indifferent_access`, etc. on the user-specified headers before setting defaults. I'd be happy to contribute a PR for either if needed/desired.

Thanks!

**Comment by nickcampbell18** [comment]
Thanks for letting us know! It should have been a string key and this was just a documentation error - we'll fix it now.
