### ISSUE TITLE
faraday 1.0.0

### ISSUE THREAD

**Issue by seb-sykio** [gocardless/gocardless-pro-ruby#57]
would be wonderful if you could upgrade to faraday 1.0.0

thanks

**Comment by StuartHadfield** [comment]
Hi @seb-sykio, thanks for the suggestion. I'll take this back to the team and discuss if we can/should upgrade at this point.

I'll update you if/when I have any news!

**Comment by stoem** [comment]
We're not on ruby >= 2.3 yet so this could be a problem for us.

**Comment by seb-sykio** [comment]
hi
thanks for your message. We are already using your gem on ruby 2.6.5, and we dont have any problem

**Comment by schinery** [comment]
Hey @StuartHadfield, any news on whether this Faraday upgrade might happen?

**Comment by mhenrixon** [comment]
Would also love a move towards 1.0

**Comment by nickcampbell18** [comment]
Hey folks just preparing a release for this now, should go out shortly!

**Comment by mbaird** [comment]
Thanks @nickcampbell18!
