### ISSUE TITLE
session.id not raising an error during redirect flow creation since update of update of rails 6.0.2.1

### ISSUE THREAD

**Issue by lioneldebauge** [gocardless/gocardless-pro-ruby#67]
Hi GC team,

Since update of rails 6.0.2.1 a new version of rack has been integrated. Rack has changed the behavior of `session.id` which does not render a string anymore but an object called `Rack::Session::SessionId`. This does not work well with the creation of a redirect flow in our system since I believe GC is expecting a string not an instance of an object and therefore raise the following error.

```
GoCardlessPro::InvalidApiUsageError at /book/stays/1/profile/start_payment_setup
One of your parameters was incorrectly typed
```

A fix advised by Rails team is to do `session.id&.public_id` which does render a string. However my team and I think it would be more efficient to have a fix directly done by you guys. Would you consider it ?

**Comment by matthieuprat** [comment]
Hey @lioneldebauge, sorry for the late reply.

Can you provide a sample of your code so that we can reproduce the error?

**Comment by lioneldebauge** [comment]
Hey @matthieuprat thanks for reaching out !

Simplied version of the code we have:

In the controller

```
class ProfilesController < ApplicationController

  def start_payment_setup
    redirect_url = PaymentOperation::GocardlessPaymentManager.new(@stay.residence).create_redirect_flow(
      profile: @profile,
      session_id: session.id,
      success_url: payment_setup_success_hook_stay_profile_url,
      incl_deposit: false
    )

    redirect_to redirect_url
  end
end
```

In our payment module

```
module PaymentOperation
  class GocardlessPaymentManager
    include DateHelper

    def initialize(residence)
      @client = GoCardlessPro::Client.new(
        access_token: PaymentOperation::GocardlessAccessTokenManager.retrieve_token(residence),
        environment: ENV['GC_ENVIRONMENT'].to_sym
      )
    end

    def create_redirect_flow(profile:, session_id:, success_url:, incl_deposit: true)
      redirect_flow = @client.redirect_flows.create(
        params: {
          description: description,
          session_token: session_id,
          success_redirect_url: success_url,
          prefilled_customer: {
            given_name: profile.given_name,
            family_name: profile.family_name,
            email: profile.email,
            language: "en"
          }
        }
      )

      redirect_flow.redirect_url
    end
  end
end
```


And here is what I have done to spot the issue
```
# Rails 6.0.2
puts session.id
=> bd659c56598cc9c15c92a262490f89e2
puts session.id.class
=> Rack::Session::SessionId

# above Rails 6.0.2
puts session.id.public_id
=> bd659c56598cc9c15c92a262490f89e2
puts session.id.public_id.class
=> String

```
For more general info on the issue you can also see
rails/rails#38039
rack/rack#1432 (comment)

**Comment by matthieuprat** [comment]
Thanks!

So, you're correct: the `session_token` parameter should be a string. If a `Rack::Session::SessionId` instance is provided instead, it will get serialized as a JSON object, which will be rejected by the API.

While we could technically cast the `session_token` to a string, casting parameters is not something we usually do in our client libraries and I'm a bit reluctant to set a precedent here.

Thank you for raising this issue though. I believe other people will benefit from it!
