### ISSUE TITLE
Ruby 2.7 Deprecation message

### ISSUE THREAD

**Issue by Nerian** [gocardless/gocardless-pro-ruby#74]
Hi,

I get the following deprecation message:

```
/Users/Nerian/.rvm/gems/ruby-2.7.1/gems/gocardless_pro-2.22.0/lib/gocardless_pro/services/customers_service.rb:162: warning: URI.escape is obsolete
```

I am running Ruby 2.7.1 I think you need to use of one CGI.escape, URI.encode_www_form or URI.encode_www_form_component.

**Comment by nickcampbell18** [comment]
Thanks for the report! I'll try and get a patch out today.

**Comment by nickcampbell18** [comment]
@Nerian this has been released, see https://github.com/gocardless/gocardless-pro-ruby/releases/tag/v2.22.1

**Comment by Nerian** [comment]
Thx!
