### ISSUE TITLE
Invalid document structure for Instalment Schedules Create with Dates

### ISSUE THREAD

**Issue by damienlethiec** [gocardless/gocardless-pro-ruby#83]
Hi there,

I am testing the GoCardless API before using it in a project and cannot make an instalment schedules creation.

First, the getting started doc is not up to date as the create method does not exist anymore (https://developer.gocardless.com/getting-started/api/taking-your-first-payment/).

Second, when I use the create_with_dates method, even with the example params for the docs, I get an Invalid Document Structure error.

Here is my request:
```
instalment_schedule = client.instalment_schedules.create_with_dates(
  params: {
    name: "ACME Invoice 103",
    amount: 10_000, # 100 GBP in pence, collected from the customer
    app_fee: 10, # Your 10 pence fee, applied to each instalment,
                 # to be paid out to you
    currency: 'GBP',
    instalments: [
      {
        charge_date: '2020-10-20',
        amount: 3_400
      },
      {
        charge_date: '2020-11-03',
        amount: 3_400
      },
    ],
    links: {
      mandate: 'A correct mandate'
    },
    metadata: {}
  },
  headers: {
    'Idempotency-Key': 'random_instalment_schedule_specific_string'
  }
)
```

Here is the response:
`GoCardlessPro::InvalidApiUsageError: Invalid document structure
from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gocardless_pro-2.24.0/lib/gocardless_pro/middlewares/raise_gocardless_errors.rb:15:in `on_complete'`

Could you help me with this?

Thanks a lot in advance :)

**Comment by paprikati** [comment]
I've created a ticket, we should take a look today. Are you able to share the request ID from the request that you've made?

**Comment by paprikati** [comment]
Hi,
unfortunately there's a typo in our docs (I'm just fixing now).
The `amount` key at the top level needs to be `total_amount` - then you should stop getting the error.

Sorry about that!
