### ISSUE TITLE
Bump 

### ISSUE THREAD

**Issue by EmmaB** [gocardless/gocardless-pro-ruby#88]
Hi, just to let you know the version that bundles is 2.25.0, and the version with `billing_requests` in (which feature so heavily in your docs) is 2.27.0. Might want to bump the gem to point to your `master` branch. Thanks!

**Comment by vdandugc** [comment]
Thank you for raising this, we will take a look and fix this ASAP.

**Comment by vdandugc** [comment]
this is done , latest version 2.27.0 is available.
