### ISSUE TITLE
Upgrade Faraday >= 2.0

### ISSUE THREAD

**Issue by schinery** [gocardless/gocardless-pro-ruby#97]
Are there any plans to upgrade to Faraday to 2.0?

**Comment by schinery** [comment]
I had a go myself, would be great if someone could take a look and give some feedback.

https://github.com/gocardless/gocardless-pro-ruby/pull/99

**Comment by mjaidi** [comment]
I would like to re-iterate the same question. Are there any plans to upgrade to Faraday > 2
